projects:
  app:
    extensions:
      endpoints:
        default: http://localhost:3000
  database:
    schemaPath: database/generated/prisma-types.graphql
    extensions:
      prisma: database/prisma.yml
      endpoints:
        default: https://eu1.prisma.sh/nikita-kot-5fc7f8/beer-advisor-be/dev
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/prisma/prisma.bindings.generated.ts
